### ISSUE TITLE
An error when asking KV for nonexisting key

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapitaBusinessNetwork/config#1]
resolve(result.Value);
                                             ^
TypeError: Cannot read property 'Value' of undefined
    at config/index.js:50:19

1. A graceful error handling should be implemented with pointing what key does not exist in KV store.  The same with services/endpoints.
2. Several attempts are taken at connection initiation with Consul.  Why not do the same when calling kv.get() and catalog.service.nodes() ?

**Comment by celber** [comment]
1) you right. I have seen the error just yesterday 

2) initialization should wait for consul to be running. Why would you like to wait for key value?

Wysłane z iPhone'a

Dnia 05.02.2017 o godz. 11:59 Andrei Mourzenkov <notifications@github.com> napisał(a):

**Comment by amourzenkov-sc** [comment]
On 05.02.2017 14:04, celber wrote:
> 1) you right. I have seen the error just yesterday
>
> 2) initialization should wait for consul to be running. Why would you
> like to wait for key value?
For the same reason we wait for consul to be running.  KVs population
takes some time after consul initialization => DB-related KVs are not in
the store yet when requested right after consul is up.

**Comment by celber** [comment]
Good to know, but stills we should wait till DB is populated during initialization 

Wysłane z iPhone'a

Dnia 05.02.2017 o godz. 12:08 Andrei Mourzenkov <notifications@github.com> napisał(a):

**Comment by amourzenkov-sc** [comment]
May be I miss smth but I do not know any means to know when DB-related
KVs get populated into Consul's store.  Any suggestions?

**Comment by celber** [comment]
No idea, need to read docs for this 

Wysłane z iPhone'a

Dnia 05.02.2017 o godz. 12:14 Andrei Mourzenkov <notifications@github.com> napisał(a):
