### ISSUE TITLE
getProperty doesn't reject the Promise when key doesn't exist

### ISSUE THREAD

**Issue by patrykkopycinski** [OpusCapitaBusinessNetwork/config#3]
It resolves the Promise with `undefined` instead of reject the Promise

**Comment by kwierchris** [comment]
I need to know the exact circumstances when this happens. My tests do not show such a problem. I even extended one test to exactly hit your problem but its result is absolutely correct.

**Comment by kwierchris** [comment]
Arne had a similar problem. Switching to a version > 2.2 helped.
